transform_tolerance: 0.5

# --- Engel Algılama Mesafeleri ---
obstacle_range: 2.5
raytrace_range: 3.0

# --- ROBOT ŞEKLİ ---
robot_radius: 0.20

# --- Şişirme (Güvenlik Alanı) ---
# ROBOTU TIR SANMASINI ENGELLEDİK! 
inflation_radius: 0.25      # 0.55'ten 0.25'e düşürüldü.
cost_scaling_factor: 10.0   # 3.0'dan 10.0'a çıkarıldı. (Artık sadece tam dibi tehlikeli)

# --- Sensör Kaynakları ---
observation_sources: laser_scan_sensor

# --- Lidar Yapılandırması ---
laser_scan_sensor: 
  sensor_frame: laser
  data_type: LaserScan
  topic: /scan
  marking: true
  clearing: true
